# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm install hexo-cli --save -g
      - run: npm install hexo-deployer-git --save -g

#      - run: yarn global add hexo-cli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
#      - run: yarn run build
      - run: ls
      - run: pwd

      - run:
          name: test
          command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                ls
#                ./node_modules/.bin/hexo clean
                #yarn global add hexo-deployer-git --save
                hexo clean
                hexo generate
                hexo deploy
                ls
